language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
services:
  - postgresql
before_script:
  - export APP_SETTINGS=testing
  - psql -c 'CREATE DATABASE test_questioner' -U postgres

env:
  - DATABASE_TEST_URL='postgresql://joshua_kodhe:12345@localhost:5432/test_questioner'
script:
  - pytest --cov-report term-missing --cov=app
  - coveralls

after_success:
  - coveralls
  - codeclimate-test-reporter
