language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
services:
  - postgresql
before_script:
  - export APP_SETTINGS=testing
  - psql -c "CREATE USER joshua_kodhe WITH PASSWORD '12345';"
  - psql -c 'CREATE DATABASE test_questioner owner joshua_kodhe;'

env:
  - DATABASE_TEST_URL='postgresql://joshua_kodhe:12345@localhost:5432/test_questioner'
script:
  - pytest
  - coverage run --source=app.api.v2 -m pytest && coverage report

after_success:
  - coveralls
  - codeclimate-test-reporter
